### PR TITLE
Support for comparing layer-by-layer output

### PR DESCRIPTION
**Pull request by Duchstf**
This is just some preliminary codes for comparing layer-by-layer output. Current implementation requires the user to convert the config file in debug mode, and then use the compare function to produce the plot depicting the differences of each layer. The printing code has been absorbed by Vladimir earlier so it won't appear in this PR. 

I still have some points to discuss, since this is far from optimal:

1. The user currently still has to convert the config in debug mode first and then use `compare`, do we want to automatically run convert in debug mode when the user pass the config to `compare`, and then automatically read the printed out outputs? 

2. Currently, I'm just calculating the distance between two output's vectors by using `np.linalg.norm`, but I'm sure there is a better way ...

### CODE REVIEW

**Comment by Duchstf** [comment]
@vloncar Just a quick note ... I'm assuming that the output txt files are printed out using this format:

```
'{project_dir}/tb_data/{layer name}_output.log'
```

**Comment by Duchstf** [comment]
Note about API:

```
#Run hls4ml convert manually in debug mode
#load keras_model
#load X
#load hls_model
figure = compare(keras_model, hls_model, X)
```

**Comment by vloncar** [comment]
Yup, it will be in that format, although I am still thinking whether to write binary instead of textual. Whatever we end up with it will be trivial to adapt the read/write functions.

**Comment by thesps** [comment]
This looks cool! I should use the `is_ignored_layer` for the other profiling too. I think the `_get_ymodel_keras` and `_get_ysim*` methods should be exposed to the user, so they can do whatever comparison they like afterwards.
And then we should think of what comparisons we should natively provide. 
For this, I think an API like `def compare(keras_model, hls_model, X, file_based=True, plot_type='diff'):` would be good, and we write a few methods to visualise the `y_model`, `y_sim` differences. These could be, for example, the absolute difference, the relative difference and anything else we can think of.

**Comment by Duchstf** [comment]
@vloncar I think binary output file is probably a better idea, since using `np.loadtxt` is running quite slow for me.

**Comment by Duchstf** [comment]
Note that I also add os detection code in build script,  remove `#include<complex>` in `parameters.h`. Also the hls_model's outputs are now numpy array (with the same shape as keras's outputs) instead of `list`.

**Comment by Duchstf** [comment]
I don't know an efficient way to not use list to collect the output. However, to avoid using too much memory, I reassign the variable of the list to the converted Numpy array. Do you think this will work? I know that python has an automatic garbage collector and so it should automatically delete variables when there are no more reference to them.

**Comment by Duchstf** [comment]
One smaller issue is that if the `hls_model` is compiled prior to using `trace`, then it spits out this error:

```
~/anaconda3/lib/python3.7/site-packages/hls4ml/model/hls_model.py in trace(self, x)
    421         print('Recompiling {} with tracing'.format(self.config.get_project_name()))
    422         self.config.trace_output = True
--> 423         self.compile()
    424 
    425         top_function, ctype = self._get_top_function(x)

~/anaconda3/lib/python3.7/site-packages/hls4ml/model/hls_model.py in compile(self)
    352         lib_name = '{}/firmware/{}.so'.format(self.config.get_output_dir(), self.config.get_project_name())
    353         if self._top_function_lib is not None:
--> 354             dlclose_func = ctypes.CDLL('libdl.so').dlclose
    355             dlclose_func.argtypes = [ctypes.c_void_p]
    356             dlclose_func.restype = ctypes.c_int

~/anaconda3/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    354 
    355         if handle is None:
--> 356             self._handle = _dlopen(self._name, mode)
    357         else:
    358             self._handle = handle

OSError: dlopen(libdl.so, 6): image not found
```

**Comment by vloncar** [comment]
I think that we should use `np.asarray`, because `np.array` will make a copy while `np.asarray` mitght not.

Regarding "smaller" issue, that is actually a rather big thing, because it means that recompiling doesn't work on mac (so it is not really usable in a jupyter notebook). Looks like Mac [doesn't use](https://stackoverflow.com/questions/20169660/where-is-libdl-so-on-mac-os-x) `libdl.so`.

**Pull request merged**
